### ISSUE TITLE
Data persistence client side

### ISSUE THREAD

**Issue by AntoineTurmel** [sudofox/switch-browser#2]
It seems cookies and localStorage are wiped when the browser is closed... is the only way possible is server-side ?

**Comment by sudofox** [comment]
Hi Antoine, are you referring to the Switch browser applet's cookies/localStorage?

It does seem to have support for saving passwords, but it may wipe cookies/local storage upon applet close. I haven't done extensive testing regarding whether it retains that information upon close.

Is there a particular end you're trying to achieve? You may be able to keep your data server-side, as you mentioned.

**Comment by AntoineTurmel** [comment]
Hi @sudofox yes I'm referring to the Switch Browser Applet (the one use for captive portal)

How does saving password work ? I don't see any prompt to let me save password.
For cookies/local storage, it's wiped when you close the applet 😢 
I just want to save data client side if possible for an app I'm building, if it's not possible I'll do it server-side 😉

**Comment by jaames** [comment]
Hey @AntoineTurmel 

For some reason (security, I guess?) the Switch web applets that we've tested won't allow data to persist on the client after the applet is closed.

With that said, I don't think we ever tested for WebSQL or IndexedDB support, they might be worth a try although I wouldn't hold my breath. ¯\\\_(ツ)_/¯
